### ISSUE TITLE
Upscaling-Tool bitte fixen

### ISSUE THREAD

**Issue by janik257** [GregorBecker/SESMG#1]
- [ ]  aus living space (pre scenario) bitte building space machen

- [ ] /program_files/urban_district_upscaling/pre_processing.py - occupants=building['occupants per unit'] bitte refactoring

**Comment by janik257** [comment]
- [ ] unterscheidung zwischen EFH und MFH aufnehmen. Abhängig von der Unit machen? Unser Datensatz zwar nicht gut, aber für die Zukunft wichtig! Wir haben einfach den MW genommen!
- [ ] unterscheidung zwischen COM wir haben einfach den MW genommen, das führt vermutlich zu starken Abweichungen!

**Comment by janik257** [comment]
- [ ] nur ein standard parameter sheet

**Comment by janik257** [comment]
- [ ] unterscheidung zwischen step und flat roof treffen? daten sind im standard param vorhanden

**Comment by janik257** [comment]
- [ ] anpassen begrifflichkeiten solarthermie (siehe overleaf dok)

**Comment by janik257** [comment]
- [ ] Clustering des Wärmebedarfs? Busse anstatt der Wärmesenken zu verorten. Theoretische Clustern wir bereits da wir MFH als eine Wärmesenke betrachten. Würden wir die Busse verorten, müsste jede Wohnungseinheit eine eigene Senke haben. Vorteil wenn wir Busse verorten ist, dass der Wärmebedarf geclustert werden kann. Auf den Bus wir die Energetische Sanierung angewendet. Dann ist der Wärmebedarf "frei" und kann mit Wärmenetz geclustert werden. Energetische Sanierung kann theoretisch auch geclustert werden, z. B. Baugebiet alle Gebäude ähnliches Baujahr?

**Comment by GregorBecker** [comment]
- [ ] einheiten zeile hinzufügen

**Comment by GregorBecker** [comment]
- [ ] label anstatt component in central sheet

**Comment by GregorBecker** [comment]
- [ ] open fred als optionale Möglichkeit in die US GUI, wenn open Fred dann Daten überprüfen und aus weather Data (4) nur die fehlenden Temperaturen importieren ansonsten alle spalten.

**Comment by GregorBecker** [comment]
- [ ] heat demand ein Blatt in standard param und elec demand ein blatt in standard param

**Comment by GregorBecker** [comment]
wurden in das Hauptverzeichnis des SESMGs übernommen und kann daher geschlossen werden.
